export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  gradient: string;
  content: { h?: string; p?: string; ul?: string[] }[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "what-is-customer-retention",
    title: "What Is Customer Retention and Why Does It Matter?",
    excerpt:
      "Acquiring new customers costs 5× more than keeping existing ones. Discover what customer retention is and how it drives long-term business growth.",
    category: "Retention",
    author: "Doloyal Team",
    authorRole: "Strategy",
    date: "2026-08-01",
    readTime: "6 min read",
    gradient: "from-[#2563EB] to-[#7C3AED]",
    content: [
      {
        p: "Customer retention is the measure of how well a business keeps its existing customers returning over time. For local businesses like salons, cafes, and gyms, repeat customers generate over 70% of total revenue.",
      },
      { h: "Why retention beats acquisition" },
      {
        p: "Studies consistently show that acquiring a new customer costs 5 to 7 times more than keeping an existing one. Furthermore, a 5% increase in retention can boost overall business profitability by 25% to 95%.",
      },
      { h: "Key metrics to track" },
      {
        ul: [
          "Repeat Visit Frequency — How often a customer returns each month.",
          "Customer Lifetime Value (LTV) — Total revenue generated by a customer.",
          "Churn Rate — The percentage of customers who stop visiting.",
        ],
      },
    ],
  },
  {
    slug: "how-loyalty-programs-increase-repeat-customers",
    title: "How Loyalty Programs Increase Repeat Customers",
    excerpt:
      "Digital points and rewards give customers a reason to return to your business instead of choosing a competitor.",
    category: "Loyalty",
    author: "Doloyal Team",
    authorRole: "Growth",
    date: "2026-07-28",
    readTime: "5 min read",
    gradient: "from-[#7C3AED] to-[#D946EF]",
    content: [
      {
        p: "A well-designed loyalty program turns casual visits into regular habits. When customers know every purchase earns progress toward a reward, they prioritize your business over competitors.",
      },
      { h: "Building an effective loyalty program" },
      {
        ul: [
          "Keep rules simple — clear points per visit or rupee spent.",
          "Offer meaningful rewards — discounts, free add-ons, or exclusive perks.",
          "Eliminate paper cards — use digital phone-number based tracking.",
        ],
      },
    ],
  },
  {
    slug: "how-salons-get-more-repeat-appointments",
    title: "How Salons Can Get More Repeat Appointments",
    excerpt:
      "Practical strategies for hair salons, spas, and beauty studios to lock in re-bookings before clients leave.",
    category: "Salons",
    author: "Doloyal Team",
    authorRole: "Salons",
    date: "2026-07-20",
    readTime: "7 min read",
    gradient: "from-[#0284C7] to-[#2563EB]",
    content: [
      {
        p: "In the beauty and wellness industry, re-booking at checkout is the single most effective way to ensure repeat business. Offering automated WhatsApp reminders 4 weeks later keeps schedules full.",
      },
      { h: "Top retention tactics for salons" },
      {
        ul: [
          "Prompt re-booking at checkout before the client walks out.",
          "Send automated WhatsApp appointment reminders 24 hours prior.",
          "Offer tier rewards for regular monthly treatments.",
        ],
      },
    ],
  },
  {
    slug: "how-cafes-build-customer-loyalty",
    title: "How Cafés Can Build Customer Loyalty",
    excerpt:
      "Turn daily coffee drinkers into lifelong brand advocates using digital punch cards and surprise perks.",
    category: "Food & Beverage",
    author: "Doloyal Team",
    authorRole: "Hospitality",
    date: "2026-07-15",
    readTime: "4 min read",
    gradient: "from-[#F59E0B] to-[#EC4899]",
    content: [
      {
        p: "Cafes rely on daily visit frequency. A digital 'buy 9 coffees get 1 free' program integrated with phone numbers encourages commuters to stop by your cafe every single morning.",
      },
    ],
  },
  {
    slug: "customer-retention-strategies-for-local-businesses",
    title: "Customer Retention Strategies for Local Businesses",
    excerpt:
      "A complete guide to building lasting relationships with local customers without spending heavily on ads.",
    category: "Strategy",
    author: "Doloyal Team",
    authorRole: "Strategy",
    date: "2026-07-10",
    readTime: "8 min read",
    gradient: "from-[#10B981] to-[#06B6D4]",
    content: [
      {
        p: "Local business marketing shouldn't stop after the first sale. Implementing win-back campaigns and personalized rewards ensures your existing customer base keeps growing.",
      },
    ],
  },
  {
    slug: "how-online-booking-improves-customer-experience",
    title: "How Online Booking Improves Customer Experience",
    excerpt:
      "Letting customers book appointments 24/7 online reduces phone calls and cuts appointment no-shows.",
    category: "Booking",
    author: "Doloyal Team",
    authorRole: "Product",
    date: "2026-07-05",
    readTime: "5 min read",
    gradient: "from-[#2563EB] to-[#0284C7]",
    content: [
      {
        p: "Over 60% of online bookings occur outside standard business hours. Providing a seamless 24/7 booking page ensures you never miss a client opportunity.",
      },
    ],
  },
  {
    slug: "loyalty-programs-vs-discounts",
    title: "Loyalty Programs vs Discounts: Which Works Better?",
    excerpt:
      "Why deep discounts hurt profit margins while structured loyalty rewards build genuine brand equity.",
    category: "Growth",
    author: "Doloyal Team",
    authorRole: "Analytics",
    date: "2026-06-25",
    readTime: "6 min read",
    gradient: "from-[#7C3AED] to-[#2563EB]",
    content: [
      {
        p: "Discounts attract price-sensitive bargain hunters who leave as soon as the sale ends. Loyalty programs reward long-term value, encouraging higher average spend.",
      },
    ],
  },
  {
    slug: "turn-first-time-customers-into-regulars",
    title: "How to Turn First-Time Customers Into Regulars",
    excerpt:
      "The critical 14-day post-visit window: how automated follow-ups convert new visitors into loyal regulars.",
    category: "Retention",
    author: "Doloyal Team",
    authorRole: "Growth",
    date: "2026-06-18",
    readTime: "6 min read",
    gradient: "from-[#06B6D4] to-[#7C3AED]",
    content: [
      {
        p: "The journey from first-time guest to loyal regular requires timely engagement. A thank-you message and a welcome offer sent within 48 hours dramatically increases second visit rates.",
      },
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}