import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';

@Injectable()
export class BookingNotificationsService {
  constructor(private readonly prisma: PrismaService) {}

  async list(tenantId: string) {
    return this.prisma.notification.findMany({
      where: { tenantId },
      orderBy: { sentAt: 'desc' },
      take: 100,
    });
  }

  async send(appointmentId: string, type: string, channel: string) {
    const appointment = await this.prisma.appointment.findUnique({
      where: { id: appointmentId },
      include: { customer: true, tenant: true },
    });
    if (!appointment) throw new NotFoundException('Appointment not found');

    let template = await this.prisma.notificationTemplate.findUnique({
      where: {
        tenantId_type_channel: {
          tenantId: appointment.tenantId,
          type,
          channel,
        },
      },
    });

    if (!template) {
      template = await this.getDefaultTemplate(appointment, type, channel) as any;
    }

    const message = this.renderTemplate(template, appointment);

    const record = await this.prisma.notification.create({
      data: {
        tenantId: appointment.tenantId,
        appointmentId: appointment.id,
        customerId: appointment.customerId,
        type,
        channel,
        recipient: appointment.customer.phone,
        status: 'SENT',
        metadata: { message },
      },
    });

    const logger = { log: (msg: string) => console.log(`[Notification] ${msg}`) };
    logger.log(`Sent ${type} via ${channel} to ${appointment.customer.phone}: ${message}`);

    return record;
  }

  async sendBookingConfirmation(appointment: any) {
    return this.send(appointment.id, 'CONFIRMATION', 'SMS');
  }

  async sendReminder(appointment: any) {
    return this.send(appointment.id, 'REMINDER', 'SMS');
  }

  async sendCancellationNotice(appointment: any) {
    return this.send(appointment.id, 'CANCELLATION', 'SMS');
  }

  async createNotificationForAppointment(appointment: any, type: string, channel: string) {
    const record = await this.prisma.notification.create({
      data: {
        tenantId: appointment.tenantId,
        appointmentId: appointment.id,
        customerId: appointment.customerId,
        type,
        channel,
        recipient: appointment.customer?.phone || '',
        status: 'SENT',
        metadata: { autoGenerated: true },
      },
    });

    const logger = { log: (msg: string) => console.log(`[Notification] ${msg}`) };
    logger.log(`Auto-generated ${type} via ${channel} for appointment ${appointment.id}`);

    return record;
  }

  async listTemplates(tenantId: string) {
    return this.prisma.notificationTemplate.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
    });
  }

  async upsertTemplate(tenantId: string, dto: {
    type: string;
    channel: string;
    subject?: string;
    body: string;
  }) {
    return this.prisma.notificationTemplate.upsert({
      where: {
        tenantId_type_channel: {
          tenantId,
          type: dto.type,
          channel: dto.channel,
        },
      },
      create: {
        tenantId,
        type: dto.type,
        channel: dto.channel,
        subject: dto.subject,
        body: dto.body,
      },
      update: {
        subject: dto.subject,
        body: dto.body,
      },
    });
  }

  async deleteTemplate(tenantId: string, id: string): Promise<void> {
    const template = await this.prisma.notificationTemplate.findFirst({
      where: { id, tenantId },
    });
    if (!template) throw new NotFoundException('Template not found');
    await this.prisma.notificationTemplate.delete({ where: { id } });
  }

  private async getDefaultTemplate(appointment: any, type: string, channel: string) {
    const customerName = appointment.customer
      ? `${appointment.customer.firstName} ${appointment.customer.lastName}`.trim()
      : 'Valued Customer';

    const messages: Record<string, string> = {
      CONFIRMATION: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} is confirmed!`,
      REMINDER: `Reminder: You have an appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`,
      CANCELLATION: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} has been cancelled.`,
    };

    return {
      body: messages[type] || `Notification regarding your appointment for ${appointment.serviceName}.`,
      subject: type === 'CONFIRMATION' ? 'Booking Confirmed' : type === 'REMINDER' ? 'Appointment Reminder' : 'Appointment Cancelled',
      type,
      channel,
    };
  }

  private renderTemplate(template: any, appointment: any): string {
    const customerName = appointment.customer
      ? `${appointment.customer.firstName} ${appointment.customer.lastName}`.trim()
      : 'Valued Customer';
    const startDate = new Date(appointment.startTime).toLocaleDateString();
    const startTime = new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    return (template.body || '')
      .replace(/{{customerName}}/g, customerName)
      .replace(/{{serviceName}}/g, appointment.serviceName || '')
      .replace(/{{date}}/g, startDate)
      .replace(/{{time}}/g, startTime)
      .replace(/{{staffName}}/g, appointment.staff?.name || '');
  }
}
