import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/prisma.service';
import { EmailService, type EmailSendResult } from '../integrations/services/email.service';

@Injectable()
export class BookingNotificationsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly emailService: EmailService,
  ) {}

  async list(tenantId: string) {
    return this.prisma.notification.findMany({
      where: { tenantId },
      orderBy: { sentAt: 'desc' },
      take: 100,
    });
  }

  async send(appointmentId: string, type: string, channel: string) {
    const appointment = await this.prisma.appointment.findUnique({
      where: { id: appointmentId },
      include: { customer: true, tenant: true },
    });
    if (!appointment) throw new NotFoundException('Appointment not found');

    let template = await this.prisma.notificationTemplate.findUnique({
      where: {
        tenantId_type_channel: {
          tenantId: appointment.tenantId,
          type,
          channel,
        },
      },
    });

    if (!template) {
      template = await this.getDefaultTemplate(appointment, type, channel) as any;
    }

    const message = this.renderTemplate(template, appointment);

    if (channel === 'EMAIL' && appointment.customer?.email) {
      return this.sendAppointmentEmail(appointment, type, template?.subject || template?.type || 'Appointment Update', message);
    }

    const record = await this.prisma.notification.create({
      data: {
        tenantId: appointment.tenantId,
        appointmentId: appointment.id,
        customerId: appointment.customerId,
        type,
        channel,
        recipient: appointment.customer.phone,
        status: 'SENT',
        metadata: { message },
      },
    });

    const logger = { log: (msg: string) => console.log(`[Notification] ${msg}`) };
    logger.log(`Sent ${type} via ${channel} to ${appointment.customer.phone}: ${message}`);

    return record;
  }

  /**
   * Send an appointment email through the business's connected Resend account
   * and persist the Notification record. Never throws — booking flows must not
   * break because email delivery failed.
   */
  async sendAppointmentEmail(appointment: any, type: string, subject: string, body: string, fromEmail?: string) {
    const customerEmail = appointment.customer?.email;
    const result: EmailSendResult = customerEmail
      ? await this.emailService.sendBusinessEmail({
          tenantId: appointment.tenantId,
          to: customerEmail,
          from: fromEmail,
          subject,
          html: body,
          customerId: appointment.customerId,
          appointmentId: appointment.id,
          notificationType: type,
        })
      : { status: 'FAILED' as const, error: 'Customer has no email address.', to: '', subject };

    return this.prisma.notification.create({
      data: {
        tenantId: appointment.tenantId,
        appointmentId: appointment.id,
        customerId: appointment.customerId,
        type,
        channel: 'EMAIL',
        recipient: customerEmail || null,
        subject,
        body,
        status: result.status,
        sentAt: result.status === 'SENT' ? new Date() : null,
        metadata: { emailLogId: result.id, providerMessageId: result.providerMessageId, error: result.error },
      },
    });
  }

  async sendBookingConfirmation(appointment: any) {
    return this.send(appointment.id, 'CONFIRMATION', 'SMS');
  }

  async sendReminder(appointment: any) {
    return this.send(appointment.id, 'REMINDER', 'SMS');
  }

  async sendCancellationNotice(appointment: any) {
    return this.send(appointment.id, 'CANCELLATION', 'SMS');
  }

  async createNotificationForAppointment(appointment: any, type: string, channel: string) {
    if (channel === 'EMAIL') {
      const template = await this.getDefaultTemplate(appointment, type, channel);
      const body = this.renderTemplate(template, appointment);
      return this.sendAppointmentEmail(appointment, type, template.subject, body);
    }

    const record = await this.prisma.notification.create({
      data: {
        tenantId: appointment.tenantId,
        appointmentId: appointment.id,
        customerId: appointment.customerId,
        type,
        channel,
        recipient: appointment.customer?.phone || '',
        status: 'SENT',
        metadata: { autoGenerated: true },
      },
    });

    const logger = { log: (msg: string) => console.log(`[Notification] ${msg}`) };
    logger.log(`Auto-generated ${type} via ${channel} for appointment ${appointment.id}`);

    return record;
  }

  async listTemplates(tenantId: string) {
    return this.prisma.notificationTemplate.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
    });
  }

  async upsertTemplate(tenantId: string, dto: {
    type: string;
    channel: string;
    subject?: string;
    body: string;
  }) {
    return this.prisma.notificationTemplate.upsert({
      where: {
        tenantId_type_channel: {
          tenantId,
          type: dto.type,
          channel: dto.channel,
        },
      },
      create: {
        tenantId,
        type: dto.type,
        channel: dto.channel,
        subject: dto.subject,
        body: dto.body,
      },
      update: {
        subject: dto.subject,
        body: dto.body,
      },
    });
  }

  async deleteTemplate(tenantId: string, id: string): Promise<void> {
    const template = await this.prisma.notificationTemplate.findFirst({
      where: { id, tenantId },
    });
    if (!template) throw new NotFoundException('Template not found');
    await this.prisma.notificationTemplate.delete({ where: { id } });
  }

  private async getDefaultTemplate(appointment: any, type: string, channel: string) {
    const customerName = appointment.customer
      ? `${appointment.customer.firstName} ${appointment.customer.lastName}`.trim()
      : 'Valued Customer';

    const messages: Record<string, string> = {
      CONFIRMATION: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} is confirmed!`,
      BOOKING_CONFIRMATION: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} is confirmed!`,
      REMINDER: `Reminder: You have an appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`,
      REMINDER_24H: `Reminder: Your appointment for ${appointment.serviceName} is tomorrow at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}. We look forward to seeing you!`,
      REMINDER_2H: `Friendly reminder: Your appointment for ${appointment.serviceName} starts in 2 hours at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`,
      CANCELLATION: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} has been cancelled.`,
      CANCELLED: `Hi ${customerName}, your appointment for ${appointment.serviceName} on ${new Date(appointment.startTime).toLocaleDateString()} has been cancelled.`,
      RESCHEDULED: `Hi ${customerName}, your appointment for ${appointment.serviceName} has been moved to ${new Date(appointment.startTime).toLocaleDateString()} at ${new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`,
      THANK_YOU: `Hi ${customerName}, thank you for visiting ${appointment.tenant?.name || 'us'} today! We look forward to seeing you again.`,
    };

    return {
      body: messages[type] || `Notification regarding your appointment for ${appointment.serviceName}.`,
      subject: type === 'CONFIRMATION' || type === 'BOOKING_CONFIRMATION' ? 'Booking Confirmed'
        : type === 'REMINDER' || type === 'REMINDER_24H' || type === 'REMINDER_2H' ? 'Appointment Reminder'
        : type === 'RESCHEDULED' ? 'Appointment Updated'
        : type === 'CANCELLATION' || type === 'CANCELLED' ? 'Appointment Cancelled'
        : type === 'THANK_YOU' ? 'Thank You'
        : 'Appointment Update',
      type,
      channel,
    };
  }

  private renderTemplate(template: any, appointment: any): string {
    const customerName = appointment.customer
      ? `${appointment.customer.firstName} ${appointment.customer.lastName}`.trim()
      : 'Valued Customer';
    const startDate = new Date(appointment.startTime).toLocaleDateString();
    const startTime = new Date(appointment.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    return (template.body || '')
      .replace(/{{customerName}}/g, customerName)
      .replace(/{{serviceName}}/g, appointment.serviceName || '')
      .replace(/{{date}}/g, startDate)
      .replace(/{{time}}/g, startTime)
      .replace(/{{staffName}}/g, appointment.staff?.name || '');
  }
}
