-- AlterTable User: security fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sessions" JSONB;

-- AlterTable Tenant: extended business settings
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "coverBannerUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "faviconUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "tagline" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'en';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "dateFormat" TEXT NOT NULL DEFAULT 'DD/MM/YYYY';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "timeFormat" TEXT NOT NULL DEFAULT '12h';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT DEFAULT '#64748B';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "accentColor" TEXT DEFAULT '#F59E0B';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "fontFamily" TEXT DEFAULT 'Inter';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "registrationNumber" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "whatsapp" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "mapsUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "legalPolicies" JSONB;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "businessStatus" JSONB;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "notificationPrefs" JSONB;
