-- AlterTable
ALTER TABLE "BookingLink" ADD COLUMN IF NOT EXISTS "pageConfig" JSONB;
ALTER TABLE "BookingLink" ADD COLUMN IF NOT EXISTS "seo" JSONB;
ALTER TABLE "BookingLink" ADD COLUMN IF NOT EXISTS "domain" JSONB;
ALTER TABLE "BookingLink" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PUBLISHED';
ALTER TABLE "BookingLink" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
