"use client";

import * as React from "react";
import { BarChart3, Clock, Gauge, Inbox, Sparkles, SquareCheck, Zap } from "lucide-react";
import { Badge, Card, CardContent, Skeleton } from "@doloyal/ui";
import { api } from "@/lib/api";

type Analytics = Awaited<ReturnType<typeof api.adminGetSupportAnalytics>>;

function Metric({
  label,
  value,
  icon,
  hint,
}: {
  label: string;
  value: string | number;
  icon: React.ReactNode;
  hint?: string;
}) {
  return (
    <div className="rounded-xl border border-[rgb(var(--color-border))] bg-[rgb(var(--color-surface))] p-4">
      <div className="flex items-center gap-2 text-xs text-[rgb(var(--color-muted-foreground))]">
        <span className="text-[rgb(var(--color-primary))]">{icon}</span>
        {label}
      </div>
      <p className="mt-1.5 text-xl font-semibold text-[rgb(var(--color-foreground))]">{value}</p>
      {hint ? <p className="mt-0.5 text-[0.62rem] text-[rgb(var(--color-muted-foreground))]">{hint}</p> : null}
    </div>
  );
}

export function AnalyticsPanel() {
  const [data, setData] = React.useState<Analytics | null>(null);

  React.useEffect(() => {
    api.adminGetSupportAnalytics().then(setData).catch(() => undefined);
  }, []);

  if (!data) {
    return (
      <Card>
        <CardContent className="p-5">
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-20 w-full rounded-xl" />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  const maxDaily = Math.max(1, ...data.tickets.daily.map((d) => d.created + d.resolved));

  return (
    <Card>
      <CardContent className="space-y-6 p-5">
        <div className="flex items-center gap-2">
          <BarChart3 className="h-4 w-4 text-[rgb(var(--color-primary))]" />
          <h2 className="text-sm font-semibold text-[rgb(var(--color-foreground))]">Support analytics</h2>
          <Badge variant="outline">Last 30 days</Badge>
        </div>

        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Metric
            label="Tickets created"
            value={data.tickets.created}
            icon={<Inbox className="h-3.5 w-3.5" />}
            hint="New customer tickets"
          />
          <Metric
            label="Tickets resolved"
            value={data.tickets.resolved}
            icon={<SquareCheck className="h-3.5 w-3.5" />}
            hint="Closed in period"
          />
          <Metric
            label="Avg first response"
            value={data.tickets.avgFirstResponseHours === null ? "—" : `${data.tickets.avgFirstResponseHours}h`}
            icon={<Zap className="h-3.5 w-3.5" />}
            hint="Time to first agent reply"
          />
          <Metric
            label="Avg resolution"
            value={data.tickets.avgResolutionHours === null ? "—" : `${data.tickets.avgResolutionHours}h`}
            icon={<Clock className="h-3.5 w-3.5" />}
            hint="Time to close"
          />
        </div>

        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Metric
            label="Ask Doloyal conversations"
            value={data.ai.conversations}
            icon={<Sparkles className="h-3.5 w-3.5" />}
            hint="AI support chats started"
          />
          <Metric
            label="AI answers"
            value={data.ai.aiAnswers}
            icon={<Gauge className="h-3.5 w-3.5" />}
            hint="Replies generated by AI"
          />
          <Metric
            label="AI resolution rate"
            value={`${data.ai.aiResolutionRate}%`}
            icon={<SquareCheck className="h-3.5 w-3.5" />}
            hint="Solved without escalation"
          />
          <Metric
            label="Escalation rate"
            value={`${data.ai.escalationRate}%`}
            icon={<Clock className="h-3.5 w-3.5" />}
            hint="Chats that became tickets"
          />
        </div>

        <div>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-[rgb(var(--color-muted-foreground))]">
            Daily volume
          </p>
          <div className="flex h-28 items-end gap-1">
            {data.tickets.daily.map((d) => (
              <div
                key={d.date}
                className="group relative flex flex-1 flex-col justify-end"
                title={`${d.date} — ${d.created} created, ${d.resolved} resolved`}
              >
                <div
                  className="w-full rounded-t bg-[rgb(var(--color-primary))] opacity-80 transition-opacity group-hover:opacity-100"
                  style={{ height: `${(d.created / maxDaily) * 100}%`, minHeight: d.created ? 2 : 0 }}
                />
                <div
                  className="w-full rounded-t bg-[rgb(var(--color-success))] opacity-80 transition-opacity group-hover:opacity-100"
                  style={{ height: `${(d.resolved / maxDaily) * 100}%`, minHeight: d.resolved ? 2 : 0 }}
                />
              </div>
            ))}
          </div>
          <div className="mt-2 flex items-center gap-4 text-[0.62rem] text-[rgb(var(--color-muted-foreground))]">
            <span className="flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-sm bg-[rgb(var(--color-primary))]" /> Created
            </span>
            <span className="flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-sm bg-[rgb(var(--color-success))]" /> Resolved
            </span>
          </div>
        </div>

        {data.tickets.byCategory.length > 0 ? (
          <div className="grid gap-4 lg:grid-cols-2">
            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-[rgb(var(--color-muted-foreground))]">
                By category
              </p>
              <div className="space-y-1.5">
                {data.tickets.byCategory.map((c) => (
                  <div key={c.category} className="flex items-center justify-between gap-3 text-xs">
                    <span className="truncate text-[rgb(var(--color-foreground))]">{c.category}</span>
                    <Badge variant="outline">{c.count}</Badge>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-[rgb(var(--color-muted-foreground))]">
                By priority
              </p>
              <div className="space-y-1.5">
                {data.tickets.byPriority.map((p) => (
                  <div key={p.priority} className="flex items-center justify-between gap-3 text-xs">
                    <span className="text-[rgb(var(--color-foreground))]">{p.priority}</span>
                    <Badge variant="outline">{p.count}</Badge>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}