"use client";

import * as React from "react";
import { useParams } from "next/navigation";
import { Gift, Users, CheckCircle2, Clock3, Share2 } from "lucide-react";
import {
  PageHeader,
  KpiCard,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
  Badge,
  Button,
} from "@doloyal/ui";
import { useCurrency } from "@/lib/currency-context";
import { useBranch } from "@/lib/branch-context";
import { generateReferrals } from "@/lib/branches";
import { PageSkeleton, usePageLoading } from "@/components/branch-ui";

export default function BranchReferralsPage() {
  const params = useParams<{ branchId: string }>();
  const branchId = params.branchId;
  const { selectedBranch } = useBranch();
  const { format: fmt } = useCurrency();
  const loading = usePageLoading(420);

  const referrals = React.useMemo(() => (branchId ? generateReferrals(branchId) : []), [branchId]);

  const stats = React.useMemo(() => ({
    total: referrals.length,
    converted: referrals.filter((r) => r.status === "Converted").length,
    pending: referrals.filter((r) => r.status === "Pending").length,
    rewards: referrals.filter((r) => r.status === "Converted").reduce((s, r) => s + r.reward, 0),
  }), [referrals]);

  if (loading || !selectedBranch) return <PageSkeleton cards={3} />;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Referrals"
        description={`Referrals generated by ${selectedBranch.name} customers.`}
        actions={<Button><Share2 className="h-4 w-4" /> Share Referral Link</Button>}
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard label="Total Referrals" value={stats.total} icon={<Users className="h-5 w-5" />} accent="primary" />
        <KpiCard label="Converted" value={stats.converted} icon={<CheckCircle2 className="h-5 w-5" />} accent="success" />
        <KpiCard label="Pending" value={stats.pending} icon={<Clock3 className="h-5 w-5" />} accent="warning" />
        <KpiCard label="Rewards Given" value={stats.rewards} format={(v) => fmt(v)} icon={<Gift className="h-5 w-5" />} accent="accent" />
      </div>

      <div className="overflow-hidden rounded-[var(--radius)] border border-[rgb(var(--color-border))] bg-[rgb(var(--color-surface))]">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Referred By</TableHead>
              <TableHead>Friend</TableHead>
              <TableHead>Channel</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Reward</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {referrals.map((r) => (
              <TableRow key={r.id}>
                <TableCell className="font-medium">{r.referrer}</TableCell>
                <TableCell className="text-sm text-[rgb(var(--color-muted-foreground))]">{r.friend}</TableCell>
                <TableCell className="text-sm">{r.channel}</TableCell>
                <TableCell className="text-sm">{r.date}</TableCell>
                <TableCell>
                  <Badge variant={r.status === "Converted" ? "success" : "warning"} className="text-[0.6rem]">
                    {r.status}
                  </Badge>
                </TableCell>
                <TableCell className="text-sm font-semibold">{fmt(r.reward)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}