-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "audience" TEXT,
ADD COLUMN     "failedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "openRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "redeemRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "scheduleDate" TIMESTAMP(3),
ADD COLUMN     "sentCount" INTEGER NOT NULL DEFAULT 0;

